apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-daisym-setting
spec:
  forms:
    - group: basics
      label: 基础
      formSchema:
        - $formkit: radio
          name: indexview
          label: 主页内容
          value: posts
          options:
            - label: 个人主页
              value: index
            - label: 文章列表
              value: posts
        - $formkit: radio
          name: momentstyle
          label: 瞬间页面样式
          value: combine
          options:
            - label: 合并
              value: combine
            - label: 分开
              value: seperate
        - $formkit: radio
          name: archiveview
          label: 归档页面显示格式
          value: archive
          options:
            - label: 归档格式
              value: archive
            - label: 列表格式
              value: list
        - $formkit: radio
          name: cateandtag
          label: 分类页面是否显示标签
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false

        - $formkit: radio
          name: instantclick
          label: 局部刷新
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: date
          name: siteStartTime
          label: 建站时间
        - $formkit: text
          name: site_author
          label: 站点作者
        - $formkit: text
          name: site_icp
          label: ICP 备案


    - group: self
      label: 个人信息
      formSchema:
        - $formkit: attachment
          name: logo
          label: 头像
        - $formkit: radio
          name: logo_size
          label: 头像尺寸选择
          value: small
          options:
            - label: 小
              value: small
            - label: 中
              value: middle
            - label: 大
              value: large
        - $formkit: text
          name: name
          label: 显示名称
        - $formkit: textarea
          name: description
          label: 个人描述
        - $formkit: url
          name: github
          label: github
          validation: "url"
        - $formkit: url
          name: weibo
          label: weibo
          validation: "url"
        - $formkit: url
          name: wechat
          label: wechat
          validation: "url"
        - $formkit: url
          name: qq
          label: qq
          validation: "url"
        - $formkit: url
          name: bilibili
          label: bilibili
          validation: "url"
        - $formkit: url
          name: rss
          label: rss
          validation: "url"
        - $formkit: url
          name: email
          label: email
          validation: "url"
        - $formkit: url
          name: steam
          label: steam
          validation: "url"


    - group: sidebar
      label: 侧边栏
      formSchema:
        - $formkit: radio
          name: quote
          label: 标语
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: text
          name: quote_title
          label: 标语标题
        - $formkit: textarea
          name: quote_content
          label: 标语内容

      
        - $formkit: radio
          name: lastpost
          label: 最新文章
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: radio
          name: lastcomment
          label: 最新评论
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: radio
          name: webinfo
          label: 统计
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
    - group: custom
      label: 其他自定义
      formSchema:
        - $formkit: textarea
          name: domainmeta
          label: 域名分组meta
        - $formkit: radio
          name: baremode
          label: 域名页面纯净模式
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: radio
          name: domaincomment
          label: 域名评论
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
